server:
  port: 8018
  servlet:
    context-path: /tzapi
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 0
  connectionTimeout: 180000

  # application.yml 文件
spring:
  profiles:
    active: test


  cas:
    ignore-filters:server.servlet.context-path: /tzapi

spring.cas.logoutUrl: https://sso.bjtzeduyun.com/logout?service=
#\u76D1\u542C\u9000\u51FA\u7684\u63A5\u53E3\uFF0C\u5373\u6240\u6709\u63A5\u53E3\u90FD\u4F1A\u8FDB\u884C\u76D1\u542C
spring.cas.sign-out-filters: /*
#\u9700\u8981\u62E6\u622A\u7684\u63A5\u53E3
spring.cas.auth-filters: /*
spring.cas.validate-filters: /*
spring.cas.request-wrapper-filters: /*
spring.cas.assertion-filters: /*
#\u8868\u793A\u5FFD\u7565\u62E6\u622A\u7684\u63A5\u53E3\uFF0C\u4E5F\u5C31\u662F\u4E0D\u7528\u8FDB\u884C\u62E6\u622A
spring.cas.ignore-filters: /user/hello|/studyNews/selectByPgList|/studyNews/read|/webMessage/selectByPgList|/course/selectByPgList|/studyNews/selectByPgList|/course/selectById|/centerIntroduce/*
#spring.cas.ignore-filters: /*
#cas\u767B\u5F55\u5730\u5740
spring.cas.cas-server-login-url: https://sso.bjtzeduyun.com/login
spring.cas.cas-server-url-prefix: https://sso.bjtzeduyun.com/
spring.cas.redirect-after-validation: true
spring.cas.use-session: true


